### ISSUE TITLE
LDR to HDR?

### ISSUE THREAD

**Issue by SizheAn** [ZSDM-HDR/Zero-Shot-Diffusion-HDR#2]
Hey I'm wondering if this model can also be used for converting LDR to HDR images? Thanks a lot!

**Comment by ZSDM-HDR** [comment]
Hi, we haven't tried that yet. The model introduced in our paper was trained to generate high-quality LDR images. Besides, I guess that if feeding a low-quality LDR image of an HDR scene directly, there will be hallucinations in the output image, because this LDR image is missing a lot of information, so the MSCN as the conditional input is also missing information to constrain the generated contents.
