### ISSUE TITLE
 generate the MSCN maps code

### ISSUE THREAD

**Issue by aaronwuganglyu** [ZSDM-HDR/Zero-Shot-Diffusion-HDR#4]
Hi, Thanks for your great work.

May I have your code about generating the MSCN maps and blur images?

Thanks

**Comment by ZSDM-HDR** [comment]
Hello! We uploaded some Matlab codes under `preprocess/`, and you can refer to these scripts for your implementation. These scripts are for generating MSCN and blurred luma maps for HDR images. 
Please note that you need to prepare two txt files beforehand, one containing the filenames of all the HDR images and the other containing the lambda values corresponding to each HDR image. (You can use the script `utils/adaptive_lambda.py` in the codebase https://github.com/yael-vinker/unpaired_hdr_tmo to calculate the lambda values.) 
If you want to pre-process LDR images, the process is simpler because there is no need for global tone mapping. Then you can remove the relevant codes in the script.

**Comment by aaronwuganglyu** [comment]
thanks
